//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangThoiTrangMVC.Models.EF_FirstDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Vouchers
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public int Value { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Quantity { get; set; }
    }
}
